### ISSUE TITLE
No such file or directory: 'hachoir-metadata'

### ISSUE THREAD

**Issue by ShahaRaz** [savra0923/SplitVideo#1]
Hey, I am getting some the next error when trying to run the next lines in Google's Colab

![image](https://user-images.githubusercontent.com/55464049/121553571-0eba8f80-ca1a-11eb-9bad-dfd456f0ff83.png)

**Comment by savra0923** [comment]
I think you need to pip install hachoir

**Comment by ShahaRaz** [comment]
Yep, Solved it :D 
I didn't understand that it was a pip library 👍 
Thank you!
